### ISSUE TITLE
Another installation problem

### ISSUE THREAD

**Issue by ouboub** [zanzagaes/GPT-1-Lope#2]
Hi 

according to the README:
```
source env/bin/activate
```
but that results in  
```
Badly placed ()'s.
```

is this a shell issue? I am using tcsh

**Comment by zanzagaes** [comment]
I believe this is a shell issue, as this is unrelated to this program. Could you try using `zsh`?
If you keep having problems, I will try to reproduce the issue.

**Comment by ouboub** [comment]
>>> "z" == zanzagaes  ***@***.***> writes:

> I believe this is a shell issue, as this is unrelated to this program.
> Could you try using `zsh`? If you keep having problems, I will try to
> reproduce the issue.


It works in bash which is fine for the moment being (all me setting is
based on tcsh, so I use bash only very occasionally and it feels wired
enough for me not to use it per default. I might try zsh some day
though).

So close that issue.


-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the NATO membership of the Ukraine.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by zanzagaes** [comment]
I have reproduced the process in bash and everything seems to work well. Could you try using pure bash and making sure there are no extraneous characters in the commands?
https://asciinema.org/a/fvJPy48JYIBfHz4RLElimErLX

**Comment by zanzagaes** [comment]
I have been able to reproduce the issue. Apparently this is a [known problem with `tcsh` ](https://stackoverflow.com/questions/21656366/python-activating-environment-variables). You can solve it by changing
`source env/bin/activate` by `source env/bin/activate.csh`.
